### ISSUE TITLE
Extraction Issue w/ Nested Directories

### ISSUE THREAD

**Issue by InValidFire** [InValidFire/ghau#3]
Due to the way shutil.move handles existing directories in the destination path, currently ghau can error if trying to move files from the extracted folder to the base directory if it already exists.

I need to modify this code to look for existing directories and then modify the destination path should it be needed. This will handle that issue and correctly replace files if they already exist.

**Comment by Space-Turtle0** [comment]
Don’t do late night coding! :p
I might have a solution, just need to test it first.

**Comment by InValidFire** [comment]
Should be patched as of commit b4fa38b46513650939ea9dcf32b515741ae03d12.

Decided to use pathlib instead of os.walk() because parsing the paths in string form would've been *possible* just a lot messier.
