### ISSUE TITLE
Improve Update Detection

### ISSUE THREAD

**Issue by InValidFire** [InValidFire/ghau#4]
Currently updates are triggered if the version of the latest release is different from the version given to the Update class. I would like to expand on this to determine proper update version number comparing... but this may be limiting on the formats users would be able to use for their software.

Using the standard rule that version numbers are expected to go up I may be able to cook something up.

Split the version by the .'s and compare numbers to the format MAJOR.MICRO.PATCH should be fine for most situations. This does however raise the question on how this API should handle non-numerical phrases in the tag names. 

I am aware software will have names like "alpha", "beta", "version", and their shortened variants appended to either the end or the beginning of the version number. Should we just toss these phrases to the side and let the built in pre-release toggle for Github guide ghau on what's production ready, or perhaps try to incorporate them into the update detection system?

**Comment by Space-Turtle0** [comment]
Possibly add the option of giving the user the choice of installing that version: For example 

```python
# Detection Code here
userInput = input(“A new ‘alpha’ version has been released, update to this version? “)
if userInput = “y”:
    #update to alpha release
else:
    #ignore or update to stable release
```
Something like this possibly?

**Comment by Space-Turtle0** [comment]
Along with that (or an update)

Alpha, beta, and version could be tossed into pre-releases as that does make sense. But a warning would help, such as the code strip above.

Another thing that could help, maybe use PyGUI along with the mix? You can create a dropdown that would have all the versions available for download. This could eliminate the need for the:
`PRERELEASE` argument.

**Comment by InValidFire** [comment]
Hm, that may be a bit much. I want to try and keep the API requests required for an update as minimal as possible, which means we can't iterate through all the versions released.

We could possibly include alpha & beta filters, however come to think of it... under the current design it *will* pull the latest available release. It just doesn't know whether that release's version number is higher than the current one stored or not. It just knows it's different. Which may be all we need.

I doubt we're going to see many people roll back updates without wanting to overwrite those who had the *bad* update.

**Comment by InValidFire** [comment]
I am deciding to close this issue as upon further thinking, we do not need to impose any sort of huge update detection system on package users as any implementation could limit their freedom to version however they like. It needs to remain flexible, and to do that we're keeping it the way it is.
